print ("Olá! Sou a Carolina e já consigo rodar meus primeiros programas em Python")
print ("Estou muito feliz por aprender a programar e criar coisas incríveis com Python!")
print ("Espero continuar aprendendo e me divertindo com a programação!")
print ("Obrigada por me ajudar a aprender, professor!")
print ("Vamos continuar explorando o mundo da programação juntos!")
print ("Até a próxima aula, pessoal! Estou ansiosa para aprender mais e criar coisas incríveis com Python!")
print ("Tchau! Foi ótimo compartilhar minha jornada de aprendizado com vocês. Até a próxima!")
print ("Adeus! Continuarei praticando e me divertindo com a programação. Até a próxima, pessoal!")
print ("Até logo! Continuarei explorando o mundo da programação e criando coisas incríveis com Python. Até a próxima, pessoal!")
print ("Até mais! Continuarei aprendendo e me divertindo com a programação. Até a próxima, pessoal!")
print ("Oi, meu nome é Carolina e estou aprendendo a programar em Python! Estou fazendo um teste de como se utiliza o fim de string com o end, será que dará certo?", end='')